{% set name = "spherely" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benbovy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 40d2450881b0953048d9b214db647c3cc48af60c2a645ec49969e7687e9c5d88

build:
  number: 1
  skip: true  # [py<310 or python_impl == 'pypy']
  script: python -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
    - scikit-build-core
    - pybind11 >=2.10.0
    - libabseil
    - s2geometry
    - s2geography >=0.2.0,<0.3
    - numpy
  run:
    - python

test:
  imports:
    - spherely
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/benbovy/spherely
  summary: 'Manipulation and analysis of geometric objects on the sphere.'
  description: |
    Spherely is the counterpart of Shapely (2.0+) for manipulation and analysis
    of spherical geometric objects. It is using the widely deployed open-source
    geometry library s2geometry via the library s2geography which provides a
    GEOS compatibility layer on top of s2geometry.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://spherely.readthedocs.io/
  dev_url: https://github.com/benbovy/spherely

extra:
  recipe-maintainers:
    - benbovy
    - jorisvandenbossche
